# (C) 2026 Rodrigo Rodrigues da Silva <rodrigo@flowlexi.com>
# SPDX-License-Identifier: Apache-2.0

stages:
  - test

python:
  image: python:3.12
  stage: test
  script:
    - python -m pip install --upgrade pip
    - python -m pip install -e .[test]
    - python -m compileall -q paveclient
    - python -m pytest
